name: Personal Website CD Pipeline
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t personal-website .
        docker tag personal-website ghcr.io/sconvent/personal-website/personal-website:latest
    - name: Push the Docker image
      run: |
        docker login ghcr.io/ -u sconvent -p ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
        docker push ghcr.io/sconvent/personal-website/personal-website:latest
