name: Personal Website CD Pipeline
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cd:
    name: Build, Push and Deploy
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t personal-website .
        docker tag personal-website ghcr.io/sconvent/personal-website/personal-website:latest
    - name: Push the Docker image
      run: |
        docker login ghcr.io/ -u sconvent -p ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
        docker push ghcr.io/sconvent/personal-website/personal-website:latest
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY_DOCKERUSER }}
        known_hosts: convent.dev
    - name: Add server host key to known_hosts
      run: ssh-keyscan -H convent.dev >> ~/.ssh/known_hosts
    - name: Connect to server via SSH
      run: ssh dockeruser@convent.dev
    - name: Test connection
      run: |
        docker ps
        echo hostname:
        hostname
