name: Personal Website CD Pipeline
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t personal-website .
        docker tag personal-website docker.pkg.github.com/sconvent/personal-website/personal-website:latest
    #- name: Push the Docker image
    #  run: |
    #    docker login docker.pkg.github.com -u <USERNAME> -p <TOKEN>
    #    docker push docker.pkg.github.com/<OWNER>/<REPO>/myimage:latest
